version: "3.9"
services:
  postgres:
    build:
      context: ../
      dockerfile: container/psql-sshd.Dockerfile
      args:
        - PSWD=${PSWD}
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=kyota
      - POSTGRES_PASSWORD=qwer
      - POSTGRES_DB=stacks
    ports:
      - "12345:5432"
      - "50022:22"
    volumes:
      - type: bind
        source: ../container/volumes/bashrc-for-container 
        target: /root/.bashrc
      # - type: bind
      #   source: ../container/volumes/postgres
      #   target: /var/lib/postgresql/data


